name: Setup Python with UV
description: Install UV, setup Python, and install bcbench package

inputs:
  all-extras:
    description: "Install all optional dependencies"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
      with:
        enable-cache: true

    - name: Setup Python
      run: uv python install
      shell: pwsh

    - name: Install bcbench package
      run: uv sync ${{ inputs.all-extras == 'true' && '--all-extras' || '' }}
      shell: pwsh
